# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-15 14:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostelRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_room', models.CharField(max_length=20)),
                ('price_room', models.IntegerField()),
                ('description_full', models.CharField(max_length=250)),
                ('description_short', models.CharField(max_length=100)),
                ('places_in_room', models.IntegerField()),
                ('rating', models.IntegerField()),
                ('free_places', models.BooleanField(default=True)),
                ('date_create', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_firstname', models.CharField(max_length=25)),
                ('person_lastname', models.CharField(max_length=25)),
                ('person_middlename', models.CharField(max_length=25)),
                ('date_in', models.DateField()),
                ('date_out', models.DateField()),
                ('order_time_in', models.DateTimeField(auto_now_add=True)),
                ('order_time_out', models.DateTimeField()),
                ('is_booking', models.BooleanField(default=True)),
                ('pament', models.BooleanField(default=False)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.HostelRoom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_main', models.IntegerField()),
                ('image_standard', models.ImageField(height_field=570, upload_to='/static/media/roomimage/', width_field=380)),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.HostelRoom')),
            ],
        ),
    ]
