# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 09:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomimage',
            name='image_original',
            field=models.ImageField(max_length=255, upload_to='room', verbose_name='original file upload'),
        ),
        migrations.AlterField(
            model_name='roomimage',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roomimages', to='hostel.HostelRoom'),
        ),
    ]
