# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-02 09:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0002_auto_20160331_0937'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extuser',
            old_name='person_firstname',
            new_name='user_firstname',
        ),
        migrations.RenameField(
            model_name='extuser',
            old_name='person_lastname',
            new_name='user_lastname',
        ),
        migrations.RenameField(
            model_name='extuser',
            old_name='person_middlename',
            new_name='user_middlename',
        ),
        migrations.AddField(
            model_name='hostelroom',
            name='position',
            field=geoposition.fields.GeopositionField(default=datetime.datetime(2016, 4, 2, 9, 29, 44, 568875, tzinfo=utc), max_length=42),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='roomimage',
            name='image_original',
            field=models.ImageField(max_length=255, upload_to='/def', verbose_name='original file upload'),
        ),
    ]
