# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-15 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0003_auto_20160315_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_time_out',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
