# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-23 19:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0009_auto_20160420_0643'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amount',
            field=models.FloatField(default=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='order_time_out',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='room',
            field=models.ForeignKey(default='100', on_delete=django.db.models.deletion.CASCADE, to='hostel.HostelRoom'),
            preserve_default=False,
        ),
    ]
