# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-15 20:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0009_auto_20160315_1942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomimage',
            name='image_standard',
        ),
        migrations.AddField(
            model_name='roomimage',
            name='image_medium',
            field=models.ImageField(blank=True, max_length=255, upload_to=''),
        ),
        migrations.AddField(
            model_name='roomimage',
            name='image_original',
            field=models.ImageField(default=datetime.datetime(2016, 3, 15, 20, 33, 50, 418373, tzinfo=utc), upload_to='/var/www/hostel.te.ua/project/media/roomimage/1458073995/', verbose_name='original file upload'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roomimage',
            name='image_thumb',
            field=models.ImageField(blank=True, max_length=255, upload_to=''),
        ),
    ]
