# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-25 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0010_auto_20160423_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='extuser',
            name='is_manager',
            field=models.BooleanField(default=False, verbose_name='Manager'),
        ),
    ]
