# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-17 18:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(db_index=True, max_length=20, unique=True, verbose_name='email')),
                ('person_firstname', models.CharField(max_length=100, verbose_name='Name')),
                ('person_lastname', models.CharField(max_length=100, verbose_name='Lastname')),
                ('person_middlename', models.CharField(max_length=100, verbose_name='Middlename')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Birth date')),
                ('register_date', models.DateField(auto_now_add=True, verbose_name='Date of register')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Administrator')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name_plural': 'Users',
                'verbose_name': 'User',
            },
        ),
        migrations.CreateModel(
            name='HostelRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_room', models.CharField(max_length=20)),
                ('price_room', models.IntegerField()),
                ('description_full', models.CharField(max_length=250)),
                ('description_short', models.CharField(max_length=100)),
                ('places_in_room', models.IntegerField()),
                ('rating', models.IntegerField()),
                ('free_places', models.BooleanField(default=True)),
                ('active', models.BooleanField(default=True)),
                ('date_create', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_firstname', models.CharField(max_length=25)),
                ('person_lastname', models.CharField(max_length=25)),
                ('person_middlename', models.CharField(max_length=25)),
                ('date_in', models.DateField()),
                ('date_out', models.DateField()),
                ('order_time_in', models.DateTimeField(auto_now_add=True)),
                ('order_time_out', models.DateTimeField(blank=True)),
                ('is_booking', models.BooleanField(default=True)),
                ('payment', models.BooleanField(default=False)),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hostel.HostelRoom')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_main', models.BooleanField()),
                ('image_original', models.ImageField(max_length=255, upload_to='/default', verbose_name='original file upload')),
                ('image_medium', models.ImageField(blank=True, max_length=255, upload_to='')),
                ('image_thumb', models.ImageField(blank=True, max_length=255, upload_to='')),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.HostelRoom')),
            ],
        ),
    ]
