# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-07 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0003_auto_20160402_0929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extuser',
            name='date_of_birth',
        ),
        migrations.AddField(
            model_name='extuser',
            name='phone_number',
            field=models.CharField(default=0, max_length=12, verbose_name='Phone Number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hostelroom',
            name='location_room',
            field=models.CharField(default=0, max_length=80),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='order_time_out',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='roomimage',
            name='image_original',
            field=models.ImageField(max_length=255, upload_to='\\', verbose_name='original file upload'),
        ),
    ]
