# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-18 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0006_auto_20160415_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='person_email',
            field=models.EmailField(default=111111111, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='person_phonenumber',
            field=models.CharField(default=2222222222, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='extuser',
            name='inner_reg',
            field=models.BooleanField(default=False, verbose_name='Inner Register'),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_booking',
            field=models.BooleanField(default=False),
        ),
    ]
