# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-20 06:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0008_auto_20160419_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='deselected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='unique_href',
            field=models.CharField(default='sdadasddasdasdfr45664646', max_length=70),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='is_booking',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_time_out',
            field=models.DateTimeField(),
        ),
    ]
