# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-05 12:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0014_auto_20160428_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionprivat24',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.Order'),
        ),
    ]
